name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  discord-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git history

      - name: Format commit list
        id: commitlog
        run: |
          if git rev-parse "${{ github.event.before }}" >/dev/null 2>&1; then
            RANGE="${{ github.event.before }}..${{ github.sha }}"
          else
            RANGE="${{ github.sha }}"
          fi

          REPO_URL="https://github.com/${{ github.repository }}"
          
          # Format commit messages with clickable short hash
          COMMITS=$(git log $RANGE --pretty=format:"• [%%h]($REPO_URL/commit/%%H) – %%s by *%%an*")
          
          # Bash needs double %% to escape % in git log, convert back
          COMMITS=$(echo "$COMMITS" | sed 's/%%/%/g')

          # Send to GitHub Actions output
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo '{
            "username": "GitHub",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [
              {
                "title": "📦 New push to \"'${{ github.ref_name }}'\"",
                "description": "'"${{ steps.commitlog.outputs.commits }}"'",
                "color": 5814783,
                "footer": {
                  "text": "'"${{ github.repository }} • ${{ github.actor }}"'"
                },
                "timestamp": "'"${{ github.event.head_commit.timestamp }}"'"
              }
            ]
          }' > payload.json

          curl -X POST -H "Content-Type: application/json" \
               -d @payload.json $DISCORD_WEBHOOK