name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change this if you want another branch

jobs:
  discord-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git log

      - name: Format commit list
        id: commitlog
        run: |
          # Determine commit range
          if git rev-parse "${{ github.event.before }}" >/dev/null 2>&1; then
            RANGE="${{ github.event.before }}..${{ github.sha }}"
          else
            RANGE="${{ github.sha }}"
          fi

          # Generate commit list
          COMMITS=$(git log $RANGE --pretty=format:'• [`%h`](https://github.com/${{ github.repository }}/commit/%H) – %s by *%an*')

          # Save output
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo '{
            "username": "GitHub",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [
              {
                "title": "📦 New push to \"'${{ github.ref_name }}'\"",
                "description": "'"${{ steps.commitlog.outputs.commits }}"'",
                "color": 5814783,
                "footer": {
                  "text": "'"${{ github.repository }} • ${{ github.actor }}"'"
                },
                "timestamp": "'"${{ github.event.head_commit.timestamp }}"'"
              }
            ]
          }' > payload.json

          curl -X POST -H "Content-Type: application/json" \
               -d @payload.json $DISCORD_WEBHOOK