name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # need full history for git log ranges

      - name: Build commit list
        id: commits
        run: |
          if git rev-parse "${{ github.event.before }}" >/dev/null 2>&1; then
            RANGE="${{ github.event.before }}..${{ github.sha }}"
          else
            RANGE="${{ github.sha }}"
          fi

          REPO_URL="https://github.com/${{ github.repository }}"
          COMMITS=$(git log $RANGE --pretty=format:"• **%h** – %s by _%an_ (<$REPO_URL/commit/%H>)")

          echo "list<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PAYLOAD=$(jq -n \
            --arg title "📦 New push to \"${{ github.ref_name }}\"" \
            --arg desc "${{ steps.commits.outputs.list }}" \
            --arg footer "${{ github.repository }} • ${{ github.actor }}" \
            --arg ts "${{ github.event.head_commit.timestamp }}" \
            '{
              username: "GitHub",
              avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              embeds: [{
                title: $title,
                description: $desc,
                color: 5814783,
                footer: { text: $footer },
                timestamp: $ts
              }]
            }')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK"